apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: merhaba-dev-ops
spec:
  selector:
    app: merhaba-dev-ops
  ports:
    - protocol: "TCP"
      port: 6767 # The port that the service is running on in the cluster
      targetPort: 6767 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: merhaba-dev-ops
spec:
  selector:
    matchLabels:
      app: merhaba-dev-ops
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: merhaba-dev-ops
    spec:
      containers:
        - name: merhaba-dev-ops
          image: merhabadevops # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6767 # The port that the container is running on in the cluster